### ISSUE TITLE
Foundation Subgraph Migration

### ISSUE THREAD

**Issue by kaduanganu** [dariaag/foundation-subgraph-migration#1]
I'm trying. Please, bear with me.

https://github.com/kaduanganu/kadua-foundation-subgraph-migration

@dariaag @belopash @abernatskiy @dzhelezov

**Comment by Mishka21A** [comment]
Cool

**Comment by boce4** [comment]
Oke

**Comment by belopash** [comment]
Just a template squid with changed schema
